### ISSUE TITLE
toolbox text-logger.js

### ISSUE THREAD

**Issue by FollowTheWizard** [danielwippermann/resol-vbus-toolbox#1]
Firts of all thanks for your resol/vbus libs and software.

I tried to toolbox today and the install on my Raspberry Pi Zero 2 W  with raspian seemed fine.

Then i ran for example the text logger  and get the error that it failed due to missing file.
user rights should be fine.
run this in my home folder and the folder is owned by the user.

i also tried it with sudo

bin/resol-vbus-toolbox --path /dev/ttyACM0 --script scripts/text-logger.js
Error: ENOENT: no such file or directory, open 'log/text/20231212.csv'
    at async Object.open (node:internal/fs/promises:628:25)
    at async Script.scriptFunction (evalmachine.<anonymous>:44:20)
    at async Script.run (/home/user_name/resol-vbus-toolbox/src/script.js:33:9)
    at async ScriptManager.run (/home/user_name/resol-vbus-toolbox/src/script-manager.js:185:13)
    at async main (/home/user_name/resol-vbus-toolbox/src/main.js:271:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'log/text/20231212.csv'
}

**Comment by danielwippermann** [comment]
Hi @FollowTheWizard !

Thank you for the kind feedback!

The reason for this `ENOENT` error probably is the fact that the "log/text" directory is missing. I'll extend the "text-logger" script to create it if necessary, but in the meantime please run

`mkdir -p log/text`

to create that directory manually and restart the toolbox.

Best regards,
Daniel

**Comment by danielwippermann** [comment]
Alternatively, just `git pull` the changes I just commited. That should solve the problem without having to manually create the directory structure first.

Best regards,
Daniel
